name: Analyze
on: [pull_request]

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"
          cache: true
      - run: |
          cd app
          flutter pub get
      - name: Analyze the code
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
  typescript_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd core && yarn install
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v13
        with:
          token: ${{ github.token }}
          path: core
          file_extensions: |
            **/*.ts
